name: Syncing two repo
on: pull_request

jobs:
  check_repo:
    name: "Check if the repo is clean"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: check_repo
        run: |
          BAD_FILES=$(find . -type f -not -path "./.git/*" -wholename "*tmp/*" -or -name "*~" -or -name "*.o" -or -name "*.a" -or -name "*.so" -or -name "*.gcno" -or -name "*.gdca" -or -name "*.gcov")
          for FILES in $BAD_FILES; do
            echo "::error file=${FILE#./}, title=Unwanted file detected::${FILE#./}"
          done
          if [ "$BAD_FILES" != ""]; then
            exit 1
          fi
  
  BuildAndTest:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: buildandtest
        run: |
          apt-get install libcriterion-dev
          cmake .
          make
          rm -rf CMakeFiles CMakeCache.txt cmake_install.cmake Makefile cmake-build-debug
          mv ./tests/CMakeTest ./CMakeLists.txt
          cmake .
          make
          ./unit_tests
        timeout-minutes: 2
